name: Moodle Plugin CI

on:
  push:
  pull_request:

jobs:
  static-checks:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: utf8mb4
          MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: "8.1"
            moodle-branch: MOODLE_405_STABLE
            database: mariadb
          - php: "8.3"
            moodle-branch: MOODLE_502_STABLE
            database: pgsql

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(pwd)/ci/bin" >> "$GITHUB_PATH"
          echo "$(pwd)/ci/vendor/bin" >> "$GITHUB_PATH"
          sudo locale-gen en_AU.UTF-8

      - name: Install Moodle test site
        run: moodle-plugin-ci install --plugin ./repo/plugin/webirr --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint

      - name: Moodle code checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcs --max-warnings 0

      - name: Moodle PHPDoc checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpdoc --max-warnings 0

      - name: Validate plugin
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints

      - name: JavaScript checks
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit --fail-on-warning

      - name: Fail cancelled jobs
        if: ${{ cancelled() }}
        run: exit 1
